version: 2
jobs:
  build:
    machine:
      timezone: Asia/Tokyo
    steps:
      - checkout
      - run:
          name: chmod permissions
          command: chmod +x ./ReViewDeploy.sh
      - run:
          name: Upload to ReViewDeploy
          command: ./ReViewDeploy.sh
